devices: Add initial installer config for Xiaomi Redmi 9A/9C (dandeli…
ubports/installer-configs pull request #217
Opened 2022-12-09 11:17 UTC by muhammad23012009

…on/angelica)

Signed-off-by: Muhammad <muhammad23012009@hotmail.com>

2022-12-09 14:24 UTC, Flohack74 approved these changes

2022-12-09 14:28 UTC, amartinz requested changes

2022-12-09 14:28 UTC, amartinz commented on v2/devices/angelica.yml
> +  bootloader_from_fastbootd:
Please remove this action to fix CI.

2022-12-10 09:15 UTC, amartinz approved these changes
Somehow CI does not report back to this MR right now, but it is green.
Thanks! :)

https://github.com/ubports/installer-configs/actions/runs/3662280017

2022-12-10 12:51 UTC, merged