mimameid: Fix Droidian support
ubports/installer-configs pull request #257
Opened 2024-03-06 10:15 UTC by erikinkinen

Due to a serious problem with a lvm installation of Droidiain on mimameid, Droidian's mimameid builds were reverted to use a recovery-sideloadable zip with rootfs.img.

This pull request adapts the installer configuration to use this package type.

2024-03-07 21:24 UTC, JamiKettunen commented
Please rebase and this can be merged then too :)

2024-03-08 10:41 UTC, amartinz requested changes

2024-03-08 10:41 UTC, amartinz commented on v2/devices/mimameid.yml
> +              action: "system"
I think this should be `boot` instead of `system`?

2024-03-08 10:49 UTC, amartinz commented
Rebased and fixed CI, please have a look again if that is fine :)

2024-03-08 10:49 UTC, amartinz approved these changes

2024-03-08 10:50 UTC, erikinkinen commented
I also noticed the TWRP build for mimameid does not show the unlock screen in the beginning. So, I removed the related user action.

2024-03-08 10:50 UTC, amartinz commented
Thanks! :)

2024-03-08 10:50 UTC, merged