Add kagura config
ubports/installer-configs pull request #29
Opened 2020-08-08 17:36 UTC by konradybcio

2020-08-08 21:57 UTC, mariogrip commented
Does this config fully work? if so i can merge it now

2020-08-08 21:59 UTC, konradybcio commented
Uh I thought the only way to test it is to merge it :see_no_evil: 

But I literally copied dora which is confirmed working and changed references and the recovery checksum to that they would match kagura.

2020-08-08 22:01 UTC, mariogrip commented
> Uh I thought the only way to test it is to merge it see_no_evil
> 
> But I literally copied dora which is confirmed working and changed references and the recovery checksum to that they would match kagura.

you can test using `ubports-install -f [config]` :)

2020-08-08 22:01 UTC, konradybcio commented
Give me 5 minutes then :)

2020-08-08 22:05 UTC, konradybcio commented
I can't seem to be able to select a release channel, the list is blank.. Is that intended or perhaps it's an error on my side?

2020-08-08 22:07 UTC, mariogrip commented
> I can't seem to be able to select a release channel, the list is blank.. Is that intended or perhaps it's an error on my side?

Has the device been added to the system image server?

2020-08-08 22:08 UTC, konradybcio commented
It is on CI.. :shrug: 

https://ci.ubports.com/job/Device%20Compatibility%20Images/job/halium-kagura/

2020-08-08 22:08 UTC, mariogrip commented
> It is on CI.. shrug
> 
> https://ci.ubports.com/job/Device%20Compatibility%20Images/job/halium-kagura/

its not here yet, https://system-image.ubports.com/16.04/arm64/edge/

Give me a minute, will add it to the system image

2020-08-08 22:15 UTC, mariogrip commented
here we go: https://system-image.ubports.com/16.04/arm64/edge/kagura/ 

please try again now :)

2020-08-08 22:34 UTC, konradybcio commented
Hmm.. for some reason it keeps rebooting to recovery after the installation is complete.. let me try to investigate..

2020-08-08 22:41 UTC, konradybcio commented
Could you trigger a CI rebuild?

2020-08-08 23:15 UTC, konradybcio commented
Okay.. so something goes terribly wrong and the rootfs doesn't get installed neither to /data nor to /system.. The files from the installer reside in /data/recovery/ but they don't install..?

2020-08-15 16:39 UTC, Flohack74 commented
I had similar experience for angler... Currently for some reason the installer and/or system-image code in recovery more or less destroy the installation. It does not seem to detect halium mode correctly...

2020-08-30 21:11 UTC, Flohack74 requested changes

2020-08-30 21:11 UTC, Flohack74 commented on v1/kagura.json
> +              "url": "https://ci.ubports.com/job/Device%20Compatibility%20Images/job/halium-kagura/2/artifact/halium-unlocked-recovery_kagura.img",
Make correct version

2020-08-30 21:17 UTC, konradybcio commented on v1/kagura.json
> +              "url": "https://ci.ubports.com/job/Device%20Compatibility%20Images/job/halium-kagura/2/artifact/halium-unlocked-recovery_kagura.img",
fixed!

2020-08-30 21:52 UTC, Flohack74 approved these changes

2020-08-30 21:53 UTC, Flohack74 approved these changes

2020-08-30 21:53 UTC, merged