Update karin.json
ubports/installer-configs pull request #76
Opened 2021-02-10 12:49 UTC by stefanomelchior

Cancelled the mention to upgrade existing android installation to android 8, because it is not in the support roadmap. In fact, the devices is a legacy with only support until android 7.0 (Nougat) and kernel 3.10

2021-02-11 09:27 UTC, Flohack74 requested changes

2021-02-11 09:27 UTC, Flohack74 commented on v1/karin.json
> -    "upgrade_android": {
You need to remove that step also in line 4 "unlock"...

2021-02-11 09:39 UTC, stefanomelchior reviewed
cancelled the call of "upgrade android" in unlock

2021-02-18 10:23 UTC, Flohack74 approved these changes

2021-02-18 10:29 UTC, merged

2021-02-26 20:35 UTC, Fuseteam commented
seems this was done on v1, should it also be done on v2?